### ISSUE TITLE
add an option to specify an alternate port

### ISSUE THREAD

**Issue by blysik** [jantman/pypuppetdb-daily-report#47]
We run puppetdb on port 8080.  I don't have a way to specify this in your report tool.

**Comment by jantman** [comment]
@blysik I'm really sorry that this has sat so long. I just started work on this. I haven't touched this project since January, and it looks like the tests aren't passing because of some upstream changes in pypuppetdb. I'll try and get something out as soon as I can, but I can't say how soon that will be.

Please also note that I no longer have a running PuppetDB installation, so this is going to be effectively impossible for me to test...

**Comment by jantman** [comment]
@blysik I assume you're using PuppetDB 2.x or 3.x, right?

I have a branch that should fix this; the default is now to connect on port 8080.

Could you please give the issues/47 branch a test and see if that fixes your problem, and also confirm what PuppetDB version you're running?

You can install the branch with:

```
pip install -e git+https://github.com/jantman/pypuppetdb-daily-report.git@issues/47#egg=pypuppetdb_daily_report
```

**Comment by jantman** [comment]
I'm no longer working somewhere that runs PuppetDB. If anyone could confirm this fix ( @blysik ? ) it would be greatly appreciated.

**Comment by jantman** [comment]
Closing issue as I've abandoned this project. If anyone would like to take over as maintainer, please contact me.
